### ISSUE TITLE
未打开SdCard权限图片无法显示

### ISSUE THREAD

**Issue by hongyangAndroid** [chejdj/WanAndroid#1]
测了下，好像没有开启sdcard权限时图片都无法加载，测试手机小米8，默认无sdcard权限。

加个授权逻辑 or 改下图片库加载图片逻辑？

**Comment by chejdj** [comment]
非常感谢，已经修改了

**Comment by hongyangAndroid** [comment]
ok 感谢 准备推荐下这个项目，体验了一哈~
